### ISSUE TITLE
Refactoring. Wait... again?

### ISSUE THREAD

**Issue by vladholubiev** [vladgolubev/mdlok#3]
Now, after several months, looking back at the codebase and architecture I want to sink through the ground.

**Comment by maximromanyuk** [comment]
[JUST DO IT!](https://youtu.be/ZXsQAXx_ao0)

**Comment by SValchyshyn** [comment]
[JUST DON`T DO IT](https://www.youtube.com/watch?v=YjiSh_9dMAg)
