### ISSUE TITLE
Hah 😂

### ISSUE THREAD

**Issue by liashchynskyi** [vladgolubev/mdlok#6]
Didn't know about this project)

Tried to do something similar.

http://www.rank.ml  (Not working at this time, because mod.tanet is not responding)

API: https://github.com/liashchynskyi/tanetjson

**Comment by vladholubiev** [comment]
Nice! 👏🏻

I see you used x-ray npm package, I was looking exactly for such a thing, thanks 😅

I'll invite you to the Slack group in a moment so it's easier to chat there

**Comment by vladholubiev** [comment]
Done, check out p.liashchynskyi@gmail.com for invitation to https://fcit-dev.slack.com
